# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geocal_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1681, 1139)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 70, 1500, 1010))
        self.frame.setMinimumSize(QtCore.QSize(1010, 700))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/gc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color:rgb(91, 169, 170);\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"    color:rgb(255, 255, 255);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_detect = QtWidgets.QWidget()
        self.page_detect.setObjectName("page_detect")
        self.pushButton_upload = QtWidgets.QPushButton(self.page_detect)
        self.pushButton_upload.setGeometry(QtCore.QRect(410, 60, 261, 41))
        self.pushButton_upload.setStyleSheet("QPushButton{\n"
"    font: 12pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(75, 140, 170);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.pushButton_detect = QtWidgets.QPushButton(self.page_detect)
        self.pushButton_detect.setGeometry(QtCore.QRect(80, 610, 271, 41))
        self.pushButton_detect.setStyleSheet("QPushButton{\n"
"    font: 12pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(75, 140, 170);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.listWidget_img = QtWidgets.QListWidget(self.page_detect)
        self.listWidget_img.setGeometry(QtCore.QRect(60, 130, 1011, 311))
        self.listWidget_img.setStyleSheet("QListWidget{\n"
"    background-color: rgb(83, 170, 163);\n"
"    border: 1px solid #cccccc;\n"
"    font: 10pt \"幼圆\";\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #e6f7ff;\n"
"}")
        self.listWidget_img.setSelectionRectVisible(False)
        self.listWidget_img.setObjectName("listWidget_img")
        self.pushButton_change = QtWidgets.QPushButton(self.page_detect)
        self.pushButton_change.setGeometry(QtCore.QRect(80, 480, 271, 41))
        self.pushButton_change.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_change.setObjectName("pushButton_change")
        self.lineEdit_output = QtWidgets.QLineEdit(self.page_detect)
        self.lineEdit_output.setGeometry(QtCore.QRect(400, 490, 661, 31))
        self.lineEdit_output.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(65, 170, 163);\n"
"border-radius:5px;\n"
"}")
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_detect)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 720, 271, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_detect)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 780, 271, 41))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.progressBar_detect = QtWidgets.QProgressBar(self.page_detect)
        self.progressBar_detect.setGeometry(QtCore.QRect(410, 610, 641, 31))
        self.progressBar_detect.setStyleSheet("QProgressBar{\n"
"border-radius:5px;\n"
"\n"
"}")
        self.progressBar_detect.setMaximum(0)
        self.progressBar_detect.setProperty("value", -1)
        self.progressBar_detect.setObjectName("progressBar_detect")
        self.stackedWidget.addWidget(self.page_detect)
        self.page_calibrate = QtWidgets.QWidget()
        self.page_calibrate.setObjectName("page_calibrate")
        self.pushButton_calibrate = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_calibrate.setGeometry(QtCore.QRect(570, 350, 321, 61))
        self.pushButton_calibrate.setStyleSheet("QPushButton{\n"
"    font: 12pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(75, 140, 170);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_9.setGeometry(QtCore.QRect(70, 220, 321, 41))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit = QtWidgets.QLineEdit(self.page_calibrate)
        self.lineEdit.setGeometry(QtCore.QRect(440, 220, 631, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(65, 170, 163);\n"
"border-radius:5px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_12.setGeometry(QtCore.QRect(70, 470, 321, 41))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_13.setGeometry(QtCore.QRect(70, 110, 321, 41))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_calibrate)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 110, 631, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(65, 170, 163);\n"
"border-radius:5px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_11.setGeometry(QtCore.QRect(570, 590, 321, 61))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    font: 12pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(75, 140, 170);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_calibrate)
        self.pushButton_14.setGeometry(QtCore.QRect(70, 720, 321, 41))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"border-radius:5px;\n"
"background-color: rgb(75, 140, 170);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackedWidget.addWidget(self.page_calibrate)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Geocal calibration"))
        self.pushButton_4.setText(_translate("MainWindow", "Grid Detection"))
        self.pushButton_5.setText(_translate("MainWindow", "Calibrate"))
        self.pushButton_upload.setText(_translate("MainWindow", "Upload images"))
        self.pushButton_detect.setText(_translate("MainWindow", "Detect"))
        self.pushButton_change.setText(_translate("MainWindow", "Change results output folder:"))
        self.pushButton_7.setText(_translate("MainWindow", "See detection result image"))
        self.pushButton_8.setText(_translate("MainWindow", "Detected points coordinates"))
        self.pushButton_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.pushButton_9.setText(_translate("MainWindow", "Change results output folder:"))
        self.pushButton_12.setText(_translate("MainWindow", "Calibration Parameter"))
        self.pushButton_13.setText(_translate("MainWindow", "Choose file for calibration:"))
        self.pushButton_11.setText(_translate("MainWindow", "Generate calibration effect"))
        self.pushButton_14.setText(_translate("MainWindow", "Calibration effect image"))
import res_rc
